### ISSUE TITLE
bower.json dependency versions

### ISSUE THREAD

**Issue by zevero** [evoluteur/evolutility#14]
bower is complaining constantly about the right versions, since your bower.json is very strict about the versions of its dependncies. I think you could insert ~ in front of most version number.

So instead of

    "jquery": "2.1.4"

please use

    "jquery": "~2.1.4"

Then it will happily accept jquery v2.2.3 as well.

**Comment by zevero** [comment]
excuse me ... you would need to do 

    "jquery": "^2.1.4"

to allow v2.2.3

**Comment by evoluteur** [comment]
Done. Thanks.
