### ISSUE TITLE
Feature request - Enable to work with Parse Collections

### ISSUE THREAD

**Issue by sathishc** [evoluteur/evolutility#4]
This is more of a feature request.

Parse.com has a great backend for storing data that can also be retrieved as Backbone Collections. If there is a simple way to integrate with a Parse backend instead of localStorage, this can become an awesome front end for managing Parse objects.

I am not familiar with Backbone, hence finding it difficult to fork the code.

**Comment by evoluteur** [comment]
That's a very good idea. Parse and Evolutility seem to be a good fit. I'll look into it.
Thanks.

**Comment by evoluteur** [comment]
I was playing w/ Parse.com and I made a little project I think you will enjoy.
https://github.com/evoluteur/parse-ui
Happy New Year.
